### ISSUE TITLE
How to generate code?

### ISSUE THREAD

**Issue by magick93** [fuinorg/org.fuin.dsl.ddd#2]
Hello

Can you give some documentation or examples on how to customize generated code please.

Thanks

**Comment by michael-schnell** [comment]
Hi, 

Currently the plugin has no code generation built-in. 

I'm currently working on the [SrcGen4J Maven Plugin](https://github.com/fuinorg/srcgen4j-maven) to generate code from the DSL, but this is not really finished yet. You can find a test project here: [ddd-dsl-test](https://github.com/fuinorg/org.fuin.dsl.ddd/tree/master/ddd-dsl-test). The base is an [XML file](https://github.com/fuinorg/org.fuin.dsl.ddd/blob/master/ddd-dsl-test/srcgen4j-config.xml) that defines what templates classes to use for code generation.

If you just target Eclipse, it should also be relatively easy to clone this repository and add some Xtend templates to generate your code. See [Writing a Code Generator With Xtend](https://eclipse.org/Xtext/documentation/103_domainmodelnextsteps.html) for explanation. The Domain Model Generator can be found [here](https://github.com/fuinorg/org.fuin.dsl.ddd/blob/master/org.fuin.dsl.ddd/src/org/fuin/dsl/ddd/generator/DomainDrivenDesignDslGenerator.xtend).

Cheers,
Michael

**Comment by michael-schnell** [comment]
Addition: I'm going to add a short "How To" to the [srcgen4j-maven](https://github.com/fuinorg/srcgen4j-maven) project.
